on:
    - push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal
          components: llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-llvm-cov
          version: 0.1.0-alpha.2
      - name: Install cargo-binutils
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-binutils
          version: latest
      - name: Install rustfilt demangler
        uses: actions-rs/install@v0.1
        with:
          crate: rustfilt
          version: latest
      - name: Run test suite with code coverage
        run: cargo llvm-cov
      - name: Collect into lcov.
        run: |
          OBJECTS="$(ls target/llvm-cov-target/debug/deps/*|grep -ve'\.d$'|xargs -n1 echo -object)"
          echo $OBJECTS
          cargo cov -- export -Xdemangler=rustfilt -instr-profile=target/llvm-cov-target/rust-llvm-cov.profdata -format=lcov $OBJECTS > coverage.lcov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: coverage.lcov
          fail_ci_if_error: true
# vim: set ts=2 sw=2 sts=2:
