on:
    - push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal
          components: llvm-tools-preview
      - name: test run
        uses: yskszk63/rust-llvm-cov@HEAD
# vim: set ts=2 sw=2 sts=2:
